# TODO: Translation updated at 2021-05-12 10:09

translate polish strings:

    # game/options.rpy:24
    old "Astral Lust"
    new "Astral Lust"
# TODO: Translation updated at 2021-05-12 10:11

translate polish strings:

    # game/options.rpy:35
    old "{color=#FF424D}Game can develop thanks to all my Patrons!\n\nHigh tier Patrons:\n\nLightSkater, 95'C19, DarrDorack{/color}\n\nEditor: Strectmar\n\nMusic: Little Planet, Dreams, Ofelia's Dream from {a=https://www.bensound.com}www.bensound.com{/a},\n\n{a=https://www.zapsplat.com}www.zapsplat.com{/a}\n\nSounds: {a=https://www.zapsplat.com}www.zapsplat.com{/a}\n\nIcons:\n\n{a=https://www.game-icons.net}Lorc, Dealpouite, Guard13007, sbed and Faithtoken (some icons merged with other icons) from Game-icons.net{/a} under {a=https://creativecommons.org/licenses/by/3.0/}CC BY 3.0{/a},\n\n{a=https://www.iconpacks.net}iconpacks.net{/a}\n\nArt: {a=https://www.patreon.com/Victorius}Victorius{/a}, {a=https://www.pixabay.com}www.pixabay.com{/a}\n\nCreepypasta:\n\nAshley Rose Wellman (phone calls),\n\nAndrew LaBelle (shower),\n\nMycool of The Fear Collective (sleep),\n\nRyan Brennaman (gravedigger)\n\n\n\nModels made in {a=https://dlsoft.dmm.co.jp/detail/illusion_0030/}Honey Select 2{/a} by {a=http://www.illusion.jp}Illusion{/a}\n\nGame made possible thanks to work of these modders: Joan6694, ConQ, AiLegend, Hooh, Osland, sjjpl, Aizen53, Makoto Yuki90, 2155X, Brang-nim, KKY, dreadninja\n\n{size=-15}Legal:\n\nAstral Lust is the intellectual property of Victorius.\n\nVictorius can be contacted through Discord (https://discord.gg/rvnBC39USx) or Patreon (https://www.patreon.com/Victorius).\n\n(a) Permission is granted for this material to be shared for non-commercial purposes provided that this statement appears in the reproduced materials.\n\n(b) You may NOT sell these files or modify these files to sell, either grouped together or separately.\n\n(c) You may NOT remove or alter the credit of the creator as it is shown here and in the game's files.\n\n(d) You may redistribute these files (Astral Lust) as Astral Lust for free. Given a credit to the developer (Victorius) is provided.{/size}"
    new "{color=#FF424D}Game can develop thanks to all my Patrons!\n\nHigh tier Patrons:\n\nLightSkater, 95'C19, DarrDorack{/color}\n\nEditor: Strectmar\n\nMusic: Little Planet, Dreams, Ofelia's Dream from {a=https://www.bensound.com}www.bensound.com{/a},\n\n{a=https://www.zapsplat.com}www.zapsplat.com{/a}\n\nSounds: {a=https://www.zapsplat.com}www.zapsplat.com{/a}\n\nIcons:\n\n{a=https://www.game-icons.net}Lorc, Dealpouite, Guard13007, sbed and Faithtoken (some icons merged with other icons) from Game-icons.net{/a} under {a=https://creativecommons.org/licenses/by/3.0/}CC BY 3.0{/a},\n\n{a=https://www.iconpacks.net}iconpacks.net{/a}\n\nArt: {a=https://www.patreon.com/Victorius}Victorius{/a}, {a=https://www.pixabay.com}www.pixabay.com{/a}\n\nCreepypasta:\n\nAshley Rose Wellman (phone calls),\n\nAndrew LaBelle (shower),\n\nMycool of The Fear Collective (sleep),\n\nRyan Brennaman (gravedigger)\n\n\n\nModels made in {a=https://dlsoft.dmm.co.jp/detail/illusion_0030/}Honey Select 2{/a} by {a=http://www.illusion.jp}Illusion{/a}\n\nGame made possible thanks to work of these modders: Joan6694, ConQ, AiLegend, Hooh, Osland, sjjpl, Aizen53, Makoto Yuki90, 2155X, Brang-nim, KKY, dreadninja\n\n{size=-15}Legal:\n\nAstral Lust is the intellectual property of Victorius.\n\nVictorius can be contacted through Discord (https://discord.gg/rvnBC39USx) or Patreon (https://www.patreon.com/Victorius).\n\n(a) Permission is granted for this material to be shared for non-commercial purposes provided that this statement appears in the reproduced materials.\n\n(b) You may NOT sell these files or modify these files to sell, either grouped together or separately.\n\n(c) You may NOT remove or alter the credit of the creator as it is shown here and in the game's files.\n\n(d) You may redistribute these files (Astral Lust) as Astral Lust for free. Given a credit to the developer (Victorius) is provided.{/size}"

